stages:
    - style
    - test_code
    - test_and_create_docs
    - publish_docs

style:
    tags:
        - python
    script:
        - pyenv local $(latest_python 3.6)
        - tox -e style -i https://cosmo-pypi.phys.ethz.ch/simple
    allow_failure: true
    stage: style


tests:
    tags:
        - python
    script:
        - pyenv versions
        - pyenv local $(latest_python 2.7) $(latest_python 3.6)
        - tox -r -vv -i https://cosmo-pypi.phys.ethz.ch/simple
    stage: test_code
    artifacts:
           paths:
             - htmlcov/

docs:
    tags:
        - python
    script:
        - pyenv local $(latest_python 3.6)
        - tox -e docs -i https://cosmo-pypi.phys.ethz.ch/simple
    stage: test_and_create_docs
    dependencies:
          - tests
    artifacts:
           paths:
             - docs/_build

publish_docs:
    tags:
        - python
    script:
        - publish_docs docs/_build hope
        - create_index_html
    when: manual
    stage: publish_docs
    dependencies:
          - docs
    only:
        - master
